// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docusaurusSidebar: [{type: 'autogenerated', dirName: '.'}],

  // New sidebar for My template
  templateSidebar: [
    {type: 'category', label: 'Smart-Reception', items:[
      'intro-smart-reception',               // 1. Introduction
      'quick-start',         // 2. Quick Start
      //'auth-flow',           // 3. Authentication Flow
      //'dashboard-overview',  // 4. Dashboard Overview
      //'call-management',     // 5. Call Management
      //'call-scheduling',     // 6. Call Scheduling
      //'assistant-management',// 7. Assistant Management
      //'settings-profile',    // 8. Settings & Profile
      //'api-integration',     // 9. API Integration
      //'advanced-workflows',  // 10. Advanced Workflows
      //'troubleshooting-faq', // 11. Troubleshooting & FAQ
      //'changelog'            // 12. Changelog & Release Notes
    ]}
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
